version: '3.8'
services:
  mysql-user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: userdb
    ports:
      - "3310:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql

  mysql-menu:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: menudb
    ports:
      - "3307:3306"
    volumes:
      - mysql-menu-data:/var/lib/mysql

  mysql-order:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: orderdb
    ports:
      - "3311:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    ports:
      - "8761:8761"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8080:8080"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on:
      - discovery
      - mysql-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8081:8081"

  menu-service:
    build:
      context: .
      dockerfile: menu-service/Dockerfile
    depends_on:
      - discovery
      - mysql-menu
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-menu:3306/menudb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8082:8082"

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    depends_on:
      - discovery
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8083:8083"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on:
      - discovery
      - mysql-order
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka/
    ports:
      - "8084:8084"

volumes:
  mysql-user-data:
  mysql-menu-data:
  mysql-order-data:
  redis-data: