server:
  port: 8084

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: order-service
    producer:
      acks: all

  shardingsphere:
    props:
      sql-show: true
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: user_id
            sharding-algorithm-name: user-inline
        sharding-algorithms:
          user-inline:
            type: INLINE
            props:
              algorithm-expression: orderdb_${user_id % 2}
    datasource:
      names: orderdb_0,orderdb_1
      orderdb_0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/orderdb_0?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: password
      orderdb_1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3309/orderdb_1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

