server:
  port: 8084

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3311/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: order-service
    producer:
      acks: all

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

